INSERT INTO ACCOUNT_TYPES (type) VALUES ('USER');
INSERT INTO ACCOUNT_TYPES (type) VALUES ('STUDENT');
INSERT INTO ACCOUNT_TYPES (type) VALUES ('MENTOR');
INSERT INTO ACCOUNT_TYPES (type) VALUES ('NO_NAME');